version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: partyom/foodgram_backend
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: partyom/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: partyom/foodgram_nginx
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/var/www/foodgram/media
      - ./docs/:/static/api/docs/
