# Generated by Django 3.2.3 on 2023-08-18 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_subscribe_unique_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='following',
            field=models.ForeignKey(
                help_text='Введите пользователя, на которого нужно оформить подписку',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='following',
                to=settings.AUTH_USER_MODEL,
                verbose_name='автор',
            ),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(
                help_text='Введите пользователя, который оформляет подписку',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='follower',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                help_text='Введите Email',
                max_length=254,
                unique=True,
                verbose_name='Email',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                help_text='Введите имя', max_length=150, verbose_name='Имя'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                help_text='Введите фамилию',
                max_length=150,
                verbose_name='Фамилия',
            ),
        ),
    ]
